gems:
  - jekyll-sitemap
  - jekyll-paginate

plugins:
  - jekyll-paginate

sass:
  style: compact # possible values: nested expanded compact compressed


relative_permalinks: false

paginate: 2
paginate_path: "/page:num/"
inter_post_navigation: false